const STEPS=["创建项目","加载材料","经营诊断","风险研判","三情景","报告交付"];
const state={step:0,project:{name:"海湾城际酒店（模拟）",city:"厦门",rooms:80,type:"接手 + 翻牌评估"},data:{occ:.68,adr:328,revpar:223,rentRatio:.29,otaRatio:.64,laborRatio:.23,annualRent:2380000,renovation:4200000,brandFee:.052}};
const $=s=>document.querySelector(s);
function money(n){return new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',maximumFractionDigits:0}).format(n)}
function pct(n){return (n*100).toFixed(1)+'%'}
function annualRoomRevenue(occ=state.data.occ,adr=state.data.adr){return state.project.rooms*365*occ*adr}
function metrics(){const r=annualRoomRevenue();return{revenue:r,revpar:state.data.occ*state.data.adr,ebitda:r*(1-state.data.rentRatio-state.data.laborRatio-state.data.brandFee-.19),rentRatio:state.data.rentRatio,otaRatio:state.data.otaRatio}}
function scenarios(){const variants=[{name:'乐观',occ:.76,adr:355,cost:.43},{name:'基准',occ:.70,adr:338,cost:.47},{name:'压力',occ:.60,adr:305,cost:.52}];return variants.map(v=>{const revenue=annualRoomRevenue(v.occ,v.adr);const ebitda=revenue*(1-v.cost-state.data.brandFee)-state.data.annualRent;const capex=state.data.renovation;return{...v,revenue,ebitda,roi:ebitda/capex,payback:ebitda>0?capex/ebitda*12:null}})}
function risks(){const out=[];if(state.data.rentRatio>.25)out.push({level:'high',title:'租金承压',text:`当前租金占收入约 ${pct(state.data.rentRatio)}，高于演示规则 25% 警戒线。`,evidence:'经营底稿 → 年租金 / 客房收入'});if(state.data.otaRatio>.55)out.push({level:'medium',title:'渠道依赖偏高',text:`OTA 占比 ${pct(state.data.otaRatio)}，获客成本和平台议价风险偏高。`,evidence:'OTA渠道月报 → 渠道结构'});if(state.data.renovation>4000000)out.push({level:'medium',title:'改造预算较重',text:`计划改造预算 ${money(state.data.renovation)}，回收期对入住率与房价提升高度敏感。`,evidence:'翻牌改造预算表 → CAPEX'});return out}
function renderStepper(){const box=$('#stepper');box.innerHTML=STEPS.map((x,i)=>`<div class="step ${i===state.step?'active':''} ${i<state.step?'done':''}" data-i="${i}">${i+1}. ${x}</div>`).join('');box.querySelectorAll('.step').forEach(el=>el.onclick=()=>{const i=+el.dataset.i;if(i<=state.step)go(i)});$('#stepTitle').textContent=`${state.step+1}. ${STEPS[state.step]}`;$('#stepCounter').textContent=`${state.step+1} / 6`}
function actions(next=true,back=true){return `<div class="actions">${back&&state.step>0?'<button class="secondary-btn" id="backBtn">上一步</button>':''}${next&&state.step<5?'<button class="primary-btn" id="nextBtn">继续演示</button>':''}</div>`}
function bindNav(){const n=$('#nextBtn'),b=$('#backBtn');if(n)n.onclick=()=>go(Math.min(5,state.step+1));if(b)b.onclick=()=>go(Math.max(0,state.step-1))}
function projectStage(){const t=document.querySelector('#projectTpl').content.cloneNode(true);const stage=$('#stage');stage.innerHTML='';stage.appendChild(t);stage.insertAdjacentHTML('beforeend',actions(true,false));['hotelName','city','rooms','projectType'].forEach(id=>{const el=$('#'+id);el.onchange=()=>{state.project.name=$('#hotelName').value;state.project.city=$('#city').value;state.project.rooms=+$(' #rooms'.trim()).value;state.project.type=$('#projectType').value}});bindNav()}
function materialStage(){const files=[['经营月报.xlsx','已解析 12 个经营字段','ok'],['OTA渠道月报.xlsx','检测到渠道占比','ok'],['租赁摘要.pdf','发现租金递增条款','warn'],['品牌合作方案.pdf','已提取加盟费率','ok'],['改造预算.xlsx','发现预算敏感项','warn'],['物业信息.pdf','基础信息完整','ok']];$('#stage').innerHTML=`<div class="section-kicker">STEP 02</div><h2>加载并核验材料</h2><p class="muted">公开 Demo 使用模拟材料清单。正式产品会保留文件、字段、来源位置、确认状态和审计记录。</p><div class="file-grid">${files.map(f=>`<div class="file-card"><strong>${f[0]}</strong><span class="${f[2]}">${f[1]}</span></div>`).join('')}</div><div class="evidence-card"><strong>高影响字段确认</strong><p>年租金：${money(state.data.annualRent)} · 改造预算：${money(state.data.renovation)} · 品牌综合费率：${pct(state.data.brandFee)}</p><p class="muted">本步骤模拟“原始资料 → 标准字段 → 人工确认”的门禁。</p></div>${actions()}`;bindNav()}
function diagnosisStage(){const m=metrics();const cards=[['入住率',pct(state.data.occ),'当前经营水平'],['ADR',money(state.data.adr),'平均房价'],['RevPAR',money(m.revpar),'每间可售房收入'],['年客房收入',money(m.revenue),'按当前经营水平年化']];$('#stage').innerHTML=`<div class="section-kicker">STEP 03</div><h2>运行经营诊断</h2><p class="muted">确定性计算先处理经营指标，Agent 再负责解释、组织证据和生成下一步问题。</p><div class="metric-grid">${cards.map(c=>`<div class="metric-card"><strong>${c[0]}</strong><div class="value">${c[1]}</div><span class="muted">${c[2]}</span></div>`).join('')}</div><div class="risk-grid"><div class="risk-card medium"><strong>收入结构</strong><p>入住率尚可，ADR 提升空间有限；继续提升收入需要降低渠道依赖并改善直销。</p></div><div class="risk-card high"><strong>成本结构</strong><p>租金占比偏高，改造投入又较大，现金回收对收入提升较敏感。</p></div></div>${actions()}`;bindNav()}
function riskStage(){const rs=risks();$('#stage').innerHTML=`<div class="section-kicker">STEP 04</div><h2>决策门与风险研判</h2><div class="gate"><span class="gate-badge">研究池</span><div><strong>主判断：可继续尽调，但暂不进入投资候选池</strong><div class="muted">先处理租金承压、渠道依赖和改造预算三项关键变量，再复核项目可行性。</div></div></div><div class="risk-grid">${rs.map(r=>`<div class="risk-card ${r.level}"><strong>${r.title}</strong><p>${r.text}</p><div class="muted">证据：${r.evidence}</div></div>`).join('')}</div><div class="evidence-card"><strong>人工复核门禁</strong><p>高风险结论必须由用户确认后才能进入正式报告。模拟 Demo 不执行自动投资决策。</p></div>${actions()}`;bindNav()}
function scenarioStage(){const ss=scenarios();$('#stage').innerHTML=`<div class="section-kicker">STEP 05</div><h2>乐观 / 基准 / 压力三情景</h2><p class="muted">调整入住率、房价和成本假设，观察投资回收对关键变量的敏感程度。</p><div class="scenario-grid">${ss.map((s,i)=>`<div class="scenario-card ${i===1?'featured':''}"><h3>${s.name}情景</h3><div class="big">${pct(s.roi)}</div><p>演示 ROI</p><p>入住率 ${pct(s.occ)} · ADR ${money(s.adr)}</p><p>年收入 ${money(s.revenue)}</p><p>年经营贡献 ${money(s.ebitda)}</p><p>静态回收 ${s.payback?s.payback.toFixed(1)+' 个月':'不可回收'}</p></div>`).join('')}</div><div class="evidence-card"><strong>成立条件</strong><p>乐观情景依赖入住率、ADR 同时提升；压力情景用于测试项目在需求下滑和成本刚性下的承受能力。</p></div>${actions()}`;bindNav()}
function reportStage(){const rs=risks(),ss=scenarios();const base=ss[1];$('#stage').innerHTML=`<div class="section-kicker">STEP 06</div><h2>尽调结论与行动计划</h2><div class="gate"><span class="gate-badge">条件推进</span><div><strong>建议完成关键条款核验后再进入下一轮投资评审</strong><div class="muted">基准情景演示 ROI ${pct(base.roi)}；项目价值高度受租金、渠道结构和改造投入影响。</div></div></div><div class="action-grid"><div class="action-card"><div class="day">30</div><strong>核验底稿</strong><p>复核租赁递增条款、品牌费叠加、改造漏项和真实渠道成本。</p></div><div class="action-card"><div class="day">60</div><strong>验证经营改善</strong><p>制定直销提升、OTA 降依赖和 ADR 优化的小规模验证方案。</p></div><div class="action-card"><div class="day">90</div><strong>重跑投资模型</strong><p>以核验后的租金、CAPEX 和经营假设重算三情景并提交人工评审。</p></div></div><div class="evidence-card"><strong>证据索引</strong><p>${rs.map(x=>x.title).join(' · ')} · 基准情景 · 关键字段确认记录</p></div><div class="actions"><button class="secondary-btn" id="backBtn">上一步</button><button class="primary-btn" id="restartBtn">重新演示</button></div>`;$('#backBtn').onclick=()=>go(4);$('#restartBtn').onclick=reset}
function go(i){state.step=i;renderStepper();[projectStage,materialStage,diagnosisStage,riskStage,scenarioStage,reportStage][i]()}
function reset(){state.step=0;go(0)}
$('#resetBtn').onclick=reset;go(0);
